import Foundation

public struct PACGenerationContext: Sendable {
    public var configuration: AppConfiguration
    public var statuses: [UUID: TunnelRuntimeStatus]
    public var proxyDisabledByNetworkPolicy: Bool
    public var networkDisabledProfileIDs: Set<UUID>
    public var appendedPAC: String?

    public init(
        configuration: AppConfiguration,
        statuses: [UUID: TunnelRuntimeStatus],
        proxyDisabledByNetworkPolicy: Bool = false,
        networkDisabledProfileIDs: Set<UUID> = [],
        appendedPAC: String? = nil
    ) {
        self.configuration = configuration
        self.statuses = statuses
        self.proxyDisabledByNetworkPolicy = proxyDisabledByNetworkPolicy
        self.networkDisabledProfileIDs = networkDisabledProfileIDs
        self.appendedPAC = appendedPAC
    }
}

public enum PACGenerator {
    private static let appendedPACFunctionName = "__sshAutoTunnelExistingFindProxyForURL"

    public static func blockingProxy(port: Int) -> String {
        "PROXY 127.0.0.1:\(port)"
    }

    public static func generate(context: PACGenerationContext) -> String {
        var lines: [String] = []
        lines.append("// Generated by SSH AutoTunnel. Do not edit by hand.")
        lines.append("// Generated at \(ISO8601DateFormatter().string(from: Date()))")
        let appendedPAC = normalizedAppendedPAC(context.appendedPAC)
        if let appendedPAC {
            lines.append("// Existing PAC source is evaluated as the fallback for unmatched AutoTunnel rules.")
            lines.append("var \(appendedPACFunctionName) = (function() {")
            lines.append("  var FindProxyForURL;")
            lines.append(indent(appendedPAC))
            lines.append("  if (typeof FindProxyForURL === \"function\") {")
            lines.append("    return FindProxyForURL;")
            lines.append("  }")
            lines.append("  return function(url, host) { return \"DIRECT\"; };")
            lines.append("})();")
        }
        lines.append("function FindProxyForURL(url, host) {")
        lines.append("  host = host.toLowerCase();")

        let fallback = fallbackExpression(hasAppendedPAC: appendedPAC != nil)
        if context.proxyDisabledByNetworkPolicy {
            lines.append("  return \(fallback);")
            lines.append("}")
            return lines.joined(separator: "\n") + "\n"
        }

        let profilesByID = Dictionary(uniqueKeysWithValues: context.configuration.profiles.map { ($0.id, $0) })

        for rule in context.configuration.pacRules where rule.enabled {
            guard let profile = profilesByID[rule.profileID] else { continue }
            let status = context.statuses[profile.id] ?? TunnelRuntimeStatus(profileID: profile.id)
            let target: String
            if context.networkDisabledProfileIDs.contains(profile.id) {
                target = fallback
            } else if status.health.isUsableForPAC {
                target = "\"SOCKS5 127.0.0.1:\(status.effectiveLocalSocksPort ?? profile.localSocksPort)\""
            } else {
                target = rule.failureMode == .directFallback
                    ? fallback
                    : "\"\(blockingProxy(port: context.configuration.blockingHTTPProxyPort))\""
            }
            lines.append("  if (\(DomainPattern.pacExpression(for: rule.domainPattern))) {")
            lines.append("    return \(target);")
            lines.append("  }")
        }

        lines.append("  return \(fallback);")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private static func fallbackExpression(hasAppendedPAC: Bool) -> String {
        hasAppendedPAC ? "\(appendedPACFunctionName)(url, host)" : "\"DIRECT\""
    }

    private static func normalizedAppendedPAC(_ pac: String?) -> String? {
        guard let pac else { return nil }
        let trimmed = pac.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    private static func indent(_ pac: String) -> String {
        pac
            .components(separatedBy: .newlines)
            .map { "  \($0)" }
            .joined(separator: "\n")
    }
}
