import Foundation

public struct PACGenerationContext: Sendable {
    public var configuration: AppConfiguration
    public var statuses: [UUID: TunnelRuntimeStatus]
    public var proxyDisabledByNetworkPolicy: Bool

    public init(configuration: AppConfiguration, statuses: [UUID: TunnelRuntimeStatus], proxyDisabledByNetworkPolicy: Bool = false) {
        self.configuration = configuration
        self.statuses = statuses
        self.proxyDisabledByNetworkPolicy = proxyDisabledByNetworkPolicy
    }
}

public enum PACGenerator {
    public static func blockingProxy(port: Int) -> String {
        "PROXY 127.0.0.1:\(port)"
    }

    public static func generate(context: PACGenerationContext) -> String {
        var lines: [String] = []
        lines.append("// Generated by SSH AutoTunnel. Do not edit by hand.")
        lines.append("// Generated at \(ISO8601DateFormatter().string(from: Date()))")
        lines.append("function FindProxyForURL(url, host) {")
        lines.append("  host = host.toLowerCase();")

        if context.proxyDisabledByNetworkPolicy {
            lines.append("  return \"DIRECT\";")
            lines.append("}")
            return lines.joined(separator: "\n") + "\n"
        }

        let profilesByID = Dictionary(uniqueKeysWithValues: context.configuration.profiles.map { ($0.id, $0) })

        for rule in context.configuration.pacRules where rule.enabled {
            guard let profile = profilesByID[rule.profileID] else { continue }
            let status = context.statuses[profile.id] ?? TunnelRuntimeStatus(profileID: profile.id)
            let target: String
            if status.health.isUsableForPAC {
                target = "SOCKS5 127.0.0.1:\(profile.localSocksPort)"
            } else {
                target = rule.failureMode == .directFallback ? "DIRECT" : blockingProxy(port: context.configuration.blockingHTTPProxyPort)
            }
            lines.append("  if (\(DomainPattern.pacExpression(for: rule.domainPattern))) {")
            lines.append("    return \"\(target)\";")
            lines.append("  }")
        }

        lines.append("  return \"DIRECT\";")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }
}
